verifyConditions:
  - "@semantic-release/changelog"
  - "@semantic-release/npm"
  - "@semantic-release/github"
  - "@semantic-release/git"

prepare:
  - "@semantic-release/changelog"
  - "@semantic-release/npm"
  -
    path: "@semantic-release/git"
    assets":
      - "package.json"
      - "dist"
    message: "chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"

publish:
  - "@semantic-release/npm"
  -
    path: "@semantic-release/github"
    assets:
        - path: "dist"

success:
  - "@semantic-release/github"

fail:
  - "@semantic-release/github"
